version: '3'
services:
  frontend:
    build:
      context: ./delliv-app/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build:
      context: ./delliv-app/backend
    ports:
      - "4000:4000"
    environment:
      POSTGRES_URL: postgres://postgres:your_password@postgres:5432/your_database
    depends_on:
      - postgres
  postgres:
    image: postgres:13 
    environment:
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
